services:
  api:
    build:
      context: .
    ports:
      - "$"
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: clinic_appointments_db
    env_file:
      - .env
    networks:
      - backend


volumes:
  pgdata:

networks:
  backend
